In [33]:
import pandas as pd 
import numpy as np

In [34]:
#s ep指定分隔符
# 当出现混合类型时的解决方案:
# 1 指定dtype参数，明确告诉read_csv列的类型。
# 2 指定low_memory=False。此时，则不进行分块读取数据，而是一次性读取。|
data = pd.read_csv('power.csv',sep = ';',low_memory=False,na_values = ['?'])

In [35]:
data.shape

(2075259, 9)

In [36]:
data.dropna(how='any',axis=0,inplace=True)

In [37]:
data.shape

(2049280, 9)

In [38]:
X = pd.DataFrame(data['Global_active_power'])
y = data['Global_intensity']
# X.insert(0,'ones',1)
X.values

array([[4.216],
       [5.36 ],
       [5.374],
       ...,
       [0.938],
       [0.934],
       [0.932]])

In [39]:
def LSM(X, y):
    w = np.linalg.inv(X.T@X)@X.T@y
    return w

In [40]:
LSM(X,y)

0    4.219774
dtype: float64

In [41]:
X.values

array([[4.216],
       [5.36 ],
       [5.374],
       ...,
       [0.938],
       [0.934],
       [0.932]])

In [42]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X.values,y)
print(lr.coef_,lr.intercept_)

[4.19888516] 0.044193137581066466


In [48]:
1 - np.sum((y-lr.coef_[0]*x+lr.intercept_)**2) / np.sum((y-y.mean())**2)

0.9247207920792097

In [43]:
import numpy as np 
class MyLinearRegression:
    def __init__(self):
        pass 

    def fit(self,X,y):
        one = np.ones(shape = (X.shape[0], 1))
        X = np.concatenate([one, X], axis = 1)
        self.w = np.linalg.inv(X.T@X)@X.T@y
        self.coef_ = self.w[1:]
        self.intercept_ = self.w[0]

    def predict(self,X):
        one = np.ones(shape = (len(X), 1))
        X = np.concatenate([one, X], axis = 1)
        return X@self.w


In [44]:
x = np.linspace(0,10,100)
y = 5 * x - 2

lr = MyLinearRegression()
# 另外一种变成二维方法
lr.fit(x[:,np.newaxis],y)
print(lr.coef_,lr.intercept_)

[5.] -1.9999999999999665


In [45]:
x_new = [[30],[20]]
lr.predict(x_new)

array([148.,  98.])