In [2]:
import pandas as pd 
import numpy as np 

In [19]:
class SGD:
    def __init__(self, eta=0.1, epoch=10):
        self.eta = eta 
        self.epoch = epoch

    def fit(self, X, y):
        one = np.ones((X.shape[0],1))
        X = np.concatenate([one,X], axis=1)
        self.w = np.random.random(X.shape[1])
        for _ in range(self.epoch):
            order = np.random.permutation(len(X))
            for xi, yi in zip(X[order],y[order]):
                y_hat = self.w @ xi
                self.w += self.eta * (yi - y_hat) * xi
        return self
    def predict(self, X):
        return X @ self.w

In [9]:
from sklearn.datasets import make_regression
X, y, coef = make_regression(n_samples=1000, n_features=5, bias=2.5, coef=True,noise=5, random_state=0)
print(f"真实权重：{coef}")



真实权重：[41.20593377 66.49948238 10.71453179 60.19514224 25.96147771]


In [20]:
sgd = SGD()
sgd.fit(X,y)
print(sgd.w)

[ 1.68394312 41.84837026 65.76555548 11.84129697 61.01011133 24.4869838 ]


In [22]:
order = np.random.permutation(len(X))
for xi, yi in zip(X[order],y[order]):
    print(xi)

[ 1.21114529 -1.04525337  0.60884383  1.30184623  0.68981816]
[ 0.40431434 -0.03847666 -0.25665014 -1.1439807   0.50434358]
[-0.20694471  0.13768983 -0.75370447  0.75399147 -0.67809546]
[-1.37262965  2.01401409  1.35678725 -1.68128845 -0.8574284 ]
[ 0.15466883 -0.50723446  0.41409135 -0.03926799  1.04156839]
[ 0.27451636 -0.81299299 -0.71960439 -1.15735526 -0.89091508]
[ 1.98969308  0.02451323 -0.41783444  0.14103673 -0.37316831]
[ 0.97197029 -0.59075715 -2.08651003  0.35026592 -1.19325783]
[ 1.39856209 -1.64921697  0.17233914  0.78257888 -0.3979121 ]
[-0.5075176  -0.81579154 -0.50535832  2.49720039 -1.0518801 ]
[ 0.21132303 -0.39806148  0.02840844 -0.62192816 -0.20239426]
[-0.18290498 -1.00636552  0.21524047  0.0076175   0.89624843]
[ 0.17371185 -0.52886985 -0.32473027  0.14630445  0.56654532]
[-0.15503581 -1.64134861  1.39053397 -0.49579549  0.06606026]
[ 0.49410303 -0.67642784  0.20565667 -1.00934099  1.85855619]
[ 1.55328265 -0.54544359 -1.20766643  1.53534354  0.10729134]
[-0.7478